# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d76cdbeb47db1ed23b81ffe79c725065a0b50c8019ec5112f44d56e6ff737e18e073c68c4bcf1515fbe7b5ffad1349dccdfa3c702f6c716acb452ea7db0eecd2

test:
  secret_key_base: 849fa7534e47ddeda6f353f53258036de7b8ad5c03b8b5297ad9211e0f88ad5228609ddf4515ffbad16a5a1d441b93af732bb7d0987fd340fae653d39eb02c32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
